# -*- coding: utf-8 -*-
"""Feature engineering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17xIj79y2RuilftphYZL3lXwcuWcIJQhu
"""

import pandas as pd
import numpy as np

df=pd.read_csv(r"C:\Users\mayak\OneDrive\Desktop\fastapi\cleaned_house_data.xls") # load cleaned dataset from raw dataset

df.shape  # check the dimentions it tells how many columns we have in this data

df.head()   # understand data what we have and what is it

print(df.columns)  # to know how many features(columns) we have

df['sqft_per_bhk'] = df['total_sqft'] / df['BHK']  # create new feature to see relation of two features ,here we find  sqft_per_bhk  how much land for one sqft

print(df[['total_sqft', 'BHK', 'sqft_per_bhk']].head()) # here we check the feature is created and values

df['price_per_sqft'] = df['price'] * 100000 / df['total_sqft']  # here we create new feature the same case like as sqft_per_bhk ,we need find  one sqft price

print(df[['price', 'total_sqft', 'price_per_sqft']].head(10)) # check values

print(df.columns) # we check features why because we create some new  features

print(df[['total_sqft', 'BHK', 'sqft_per_bhk',
          'price', 'price_per_sqft']].head())  #  check and compere previous and newly created

# check negitive values ,that means if we have that's not valid data at all like sqft_per_bhk is -20 lakhs ,so thats why we need to check and decide it is valid or in valid data to improve some domain knowledge
print("sqft_per_bhk <= 0:", (df['sqft_per_bhk'] <= 0).sum()) # check any negitive values there or not 
print("price_per_sqft <= 0:", (df['price_per_sqft'] <= 0).sum()) # here same to check negitive values 

print(df[['BHK', 'sqft_per_bhk', 'price_per_sqft']].isnull().sum())  # we are created new ,so we must check there is a null values or not if we have remove using methods

print(df[['BHK', 'sqft_per_bhk', 'price_per_sqft']].describe())  # get to know basic statistics

print(df.columns) # again check ones 

print("Final Shape:", df.shape) # check with dimenstions also

df.to_csv("feature_engineered_data.csv", index=False)  # create new csv file to perform upcoming tasks like preprocessing

import os

print(os.path.exists("feature_engineered_data.csv")) # i need to check weathere newly created file existed or not 

