# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X9jYrzq207J3rimIaKr04QOFwcqAP5zd
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.compose import ColumnTransformer

df=pd.read_csv(r"C:\Users\mayak\OneDrive\Desktop\fastapi\feature_engineered_data.xls")

df.head()

df.shape

x=df.drop('price',axis=1)
y=df['price']

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

num_cols=x.select_dtypes(include=np.number).columns
num_cols

cat_cols=x.select_dtypes(include='str').columns
cat_cols

preprocessing=ColumnTransformer(
    transformers=[
        ('numerical',StandardScaler(),num_cols),
        ('catogirical',OneHotEncoder(handle_unknown='ignore'),cat_cols)
    ]
)

print("X_train:", x_train.shape)
print("X_test :", x_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

x_train_processed=preprocessing.fit_transform(x_train)
x_test_processed=preprocessing.transform(x_test)

print("X_train_processed:", x_train_processed.shape)
print("X_test_processed :", x_test_processed.shape)

print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train_processed_df = pd.DataFrame(
    x_train_processed
)

X_test_processed_df = pd.DataFrame(
    x_test_processed
)

X_train_processed_df.to_csv(
    "../data/X_train_processed.csv",
    index=False
)

X_test_processed_df.to_csv(
    "../data/X_test_processed.csv",
    index=False
)

y_train.to_csv(
    "..y_train.csv",
    index=False
)

y_test.to_csv(
    "y_test.csv",
    index=False
)

